# Verifies that the user has admin permissions, and that versions are in a sane state.
# Used as a prelude for all workflows which make changes.
#
# INPUTS
# * ref:             The ref to check out (defaults to the workflow ref)
# * assert_version:  Whether to check that version numbers are sane
name: Credential Check
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ${{ github.ref_name }}
      assert_version:
        type: boolean
        required: false
        default: true

jobs:
  credential-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if user is an administrator
        uses: actions-cool/check-user-permission@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          require: admin

      - name: Checkout repository
        if: ${{ inputs.assert_version }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        if: ${{ inputs.assert_version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip

      - name: Assert version
        if: ${{ inputs.assert_version }}
        run: |
          pip install -r tools/requirements-tools.txt
          python tools/assert_version.py
